### ISSUE TITLE
Request: Add ```prismlauncher``` to prebuilt

### ISSUE THREAD

**Issue by brunothedev** [makedeb/prebuilt-mpr#157]
I an asking for adding  ```prismlauncher``` to prebuilt because:

1. It is one of the best minecraft launchers
2. There is no alternative to installing on debian(except flatpak)

**Comment by hwittenborn** [comment]
Prism Launcher is already in the Prebuilt-MPR, were you having an issue installing it?

**Comment by brunothedev** [comment]
@hwittenborn 
```[brunothedev@debian ~]$ sudo apt install prismlauncher 
[sudo] senha para brunothedev: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências... Pronto
Lendo informação de estado... Pronto        
E: Impossível encontrar o pacote prismlauncher
```

If you don't know portuguese, basically, it didn't found the ```prismlauncher``` package

**Comment by hwittenborn** [comment]
@brunothedev What distro/release are you on? I'm suspecting that's the cause.

**Comment by brunothedev** [comment]
@hwittenborn Debian Sid

**Comment by brunothedev** [comment]
left debian for a better distro

**Comment by hwittenborn** [comment]
I'm sorry to hear that @brunothedev, the reason it wasn't working was because you were on Debian Sid though. The Prebuilt-MPR doesn't support it because libraries are always getting updated on it, and it'd be hard to update all the packages needing it when it does.

If there's anything I can do to help just me know though, I'd be more than glad to.

**Comment by brunothedev** [comment]
i changed my distro to opensuse tumbleweed now though
